### PR TITLE
#155: implement calculate average build duration

### PR DESCRIPTION
**Pull request by Yegorov**
@yegor256 Merge this PR [fbe#53](https://github.com/zerocracy/fbe/pull/53) before

### CODE REVIEW

**Comment by yegor256** [comment]
@Yegorov new version of fbe released

**Comment by Yegorov** [comment]
@yegor256 updated

**Comment by yegor256** [comment]
@Yegorov thanks!

**Comment by 0crat** [comment]
@Yegorov Thanks for your contribution! You've earned +5 points: +25 base, -15 for no code review, -5 for only 2 comments (policy requires at least 5), -10 for just 4 hits-of-code (min 20 required), +10 to meet the minimum reward. Remember, more [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) and thorough code reviews can significantly boost your points next time. [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions coming! Your balance: [+101](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

**Pull request merged**
