### PR TITLE
#157: implement calculate average issues for repos

### PR DESCRIPTION
**Pull request by Yegorov**

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Review by yegor256 — APPROVED** [review]
LGTM

**Comment by 0crat** [comment]
@Yegorov Thanks for the contribution! You've earned +20 points for this: +30 as a basis; -10 for too few (2) comments. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+25](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

**Comment by 0crat** [comment]
@yegor256 Thanks for the review! You've earned +15 points for this: +25 as a basis; -10 for too few (3) comments.  Your running balance is [-331](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

**Pull request merged**
