### PR TITLE
#201 count `total_commits`

### LINKED ISSUE #201: `total_commits` into DoT
Let's add `total_commits` metric to the `dimensions-of-terrain.rb` script. It should calculate the total number of commits every pushed to all repositories.

### PR DESCRIPTION
**Pull request by Suban05**
@yegor256 please merge https://github.com/zerocracy/fbe/pull/103 before

Closes #201

### CODE REVIEW

**Comment by Suban05** [comment]
@Yegorov please review

**Review by Yegorov — APPROVED** [review]
@Suban05 Looks good!

**Comment by Suban05** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@Suban05 thanks!

**Comment by 0crat** [comment]
@Suban05 Thank you for your contribution! We appreciate your effort. According to our policy, you've earned +4 points as a base reward. However, there were some areas for improvement: -4 points for having only 2 comments (less than 6), and -8 points for contributing 18 hits-of-code (less than 20). To ensure you receive at least the minimum reward, we've added +12 points, resulting in a total of +4 points. Please continue to [focus on quality and quantity](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) in your future contributions. Your updated balance is now [+135](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work!

**Pull request merged**
