### PR TITLE
#220: calculate average reviews per pr

### LINKED ISSUE #220: `average_reviews_per_pull` into QoS
Let's add `average_reviews_per_pull` metric to the `quality-of-service.rb` script. It should calculate the average number of reviews per a pull request.

Maybe relevant to #192

### PR DESCRIPTION
**Pull request by Yegorov**
Closes #220

### CODE REVIEW

**Review by Suban05 — APPROVED** [review]
@Yegorov looks good

**Comment by Yegorov** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@Yegorov thanks!

**Comment by 0crat** [comment]
@Suban05 Great job on the review! 🌟 You've earned +4 points: +4 base, -10 for limited comments, +10 bonus. Your dedication is appreciated! Current balance: [+269](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the excellent work!

**Comment by 0crat** [comment]
@Yegorov Thanks for your contribution! Your reward is +4 points, calculated as follows: +4 base, +0.85 for 17 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html), -4 for few comments (3), and +3.15 to meet the minimum. Remember, more code and reviews can boost your points! Your balance is now [+201](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work and [aim for quality](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) in your future contributions.

**Pull request merged**
