### PR TITLE
#373: fix fetch contributors if tag empty

### LINKED ISSUE #373: RuntimeError: Can't find 'tag' attribute out of ...
I found it [here](https://github.com/objectionary/eo/actions/runs/11177233856/job/31072299243):

```
RuntimeError: Can't find 'tag' attribute out of [_id, _time, _version, where, event_id, when, event_type, repository, who, release_id, what, details, is_human]
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/fact.rb:90:in `block in <class:Fact>'
	/usr/local/bundle/gems/others-0.0.3/lib/others.rb:38:in `instance_exec'
	/usr/local/bundle/gems/others-0.0.3/lib/others.rb:38:in `method_missing'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/tee.rb:54:in `block in <class:Tee>'
	/usr/local/bundle/gems/others-0.0.3/lib/others.rb:38:in `instance_exec'
	/usr/local/bundle/gems/others-0.0.3/lib/others.rb:38:in `method_missing'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/accum.rb:66:in `block in <class:Accum>'
	/usr/local/bundle/gems/others-0.0.3/lib/others.rb:38:in `instance_exec'
	/usr/local/bundle/gems/others-0.0.3/lib/others.rb:38:in `method_missing'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/rules.rb:101:in `block in <class:Fact>'
	/usr/local/bundle/gems/others-0.0.3/lib/others.rb:38:in `instance_exec'
	/usr/local/bundle/gems/others-0.0.3/lib/others.rb:38:in `method_missing'
	/action/judges/github-events/github-events.rb:51:in `fetch_contributors'
```

### PR DESCRIPTION
**Pull request by Yegorov**
Closes #373

### CODE REVIEW

**Comment by Yegorov** [comment]
@Suban05 please review

**Review by Suban05 — APPROVED** [review]
@Yegorov Looks fine!

**Comment by Yegorov** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@Yegorov thanks!

**Comment by 0crat** [comment]
@Suban05 Thank you for your code review contribution! I appreciate your effort, but there's room for improvement. According to our policy, you've earned 4 base points, but we had to deduct 16 points due to the absence of comments. To ensure you receive at least the minimum reward, we've adjusted your total to 4 points. Your current balance stands at [+112](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). For future reviews, please aim to provide more detailed feedback to maximize your points and help improve our code quality. Keep up the good work!

**Comment by 0crat** [comment]
@Yegorov Thank you for your contribution! Your effort is appreciated. Here's a breakdown of your points: +4 base points, +9.8 for 196 hits-of-code, -4 for having only 2 comments during review. Total earned: +9.8 points. While your code contribution is solid, we encourage more detailed code reviews to improve collaboration. Your current balance is [+163.8](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work and remember to [balance speed and quality](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) in your future contributions.

**Pull request merged**
