### PR TITLE
#200: calculate total number of issues and pull requests

### LINKED ISSUE #200: `total_issues` and `total_pulls` into DoT
Let's add `total_issues` metric to the `dimensions-of-terrain.rb` script. It should 
calculate the total number of all issues every reported in all repositories (excluding pulls).

Let's also calculate `total_pulls`.

### PR DESCRIPTION
**Pull request by Yegorov**
Closes #200

### CODE REVIEW

**Comment by Yegorov** [comment]
@Suban05 please review. Test fail, because this https://github.com/zerocracy/fbe/pull/101 PR need merge before

**Review by Suban05 — APPROVED** [review]
@Yegorov looks good

**Comment by Yegorov** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@Yegorov thanks!

**Comment by 0crat** [comment]
@Suban05 Hey there! 👋 Great job on the review, but we've got some room for improvement. You snagged +4 points as a base, but lost 10 due to the low comment count (only 1). We bumped you up 10 points to keep things positive. Remember, more comments can earn you up to 8 extra points! Your current balance is [+119](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work and aim for those bonus points next time! 💪

**Comment by 0crat** [comment]
@Yegorov Hey there! 👋 Thanks for your contribution! You've earned +4 points this time. Here's the breakdown: +4 base points, -4 because there were only 3 comments (we like to see more discussion!), and +4 to ensure you get something for your effort. Remember, more [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) and active code reviews can boost your points next time! [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions coming - we value your work! Your current balance is [+170](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Looking forward to your next submission! 💻🚀

**Pull request merged**
