### PR TITLE
#254 empty repository causes runtime exception at `quantity-of-deliverables.rb`

### LINKED ISSUE #254: empty repository causes runtime exception at `quantity-of-deliverables.rb`
When Git repository is empty (has no commits), I [see](https://github.com/objectionary/eo/actions/runs/10329515167/job/28597406025) this:

```
Octokit::Conflict: GET https://api.github.com/repos/objectionary/hone-maven-plugin/commits?per_page=100&since=2024-07-13T06%3A28%3A18%2B00%3A00: 409 - Git Repository is empty. // See: https://docs.github.com/rest/commits/commits#list-commits
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/response/raise_error.rb:14:in `on_complete'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/middleware.rb:57:in `block in call'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/response.rb:42:in `on_complete'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/middleware.rb:56:in `call'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:286:in `fetch'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:190:in `process'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:141:in `call!'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:121:in `call'
	/usr/local/bundle/gems/fbe-0.0.36/lib/fbe/middleware/quota.rb:41:in `call'
	/usr/local/bundle/gems/faraday-retry-2.2.1/lib/faraday/retry/middleware.rb:153:in `call'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/rack_builder.rb:152:in `build_response'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/connection.rb:444:in `run_request'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/connection.rb:200:in `get'
	/usr/local/bundle/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/connection.rb:156:in `request'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/connection.rb:84:in `paginate'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/client/commits.rb:27:in `commits'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/client/commits.rb:54:in `commits_since'
	/usr/local/bundle/gems/verbose-0.0.2/lib/verbose.rb:48:in `method_missing'
	/usr/local/bundle/gems/decoor-0.0.1/lib/decoor.rb:43:in `method_missing'
	/action/judges/quantity-of-deliverables/quantity-of-deliverables.rb:52:in `block in <top (required)>'
```

Let's try to prevent this from happening somehow. Maybe let's check the number of commits first, through `Fbe.octo.repository()` call?

### PR DESCRIPTION
**Pull request by Suban05**
* Added skipping repo if its size is 0

Fixes #254

### CODE REVIEW

**Comment by Suban05** [comment]
@Yegorov please review
tests are falling due to a bug, which will be fixed in the pull request https://github.com/zerocracy/judges-action/pull/277

**Review by Yegorov — APPROVED** [review]
@Suban05 Looks fine!

**Comment by yegor256** [comment]
@Suban05 thanks!

**Comment by 0crat** [comment]
@Yegorov Thanks for the review! You've earned +5 points: +15 base, -30 for self-review, +20 for comments (max), but only 1 comment made so -15. Your [running balance](https://zerocracy.github.io/judges-action/zerocracy-vitals.html) is now +294. Remember, more comments can boost your points next time! 💡

**Pull request merged**
