### PR TITLE
#325: fix empty author id

### LINKED ISSUE #325: `NoMethodError: undefined method `[]' for nil` in `github-events.rb`
I found it [here](https://github.com/zerocracy/judges-action/actions/runs/10698546946/job/29658188088):

```
D: Found 40 fact(s) by '(and (eq repository 799113787) (eq what 'release-published'))' in 25ms
D: Octokit::Client.compare("yegor256/judges", "0.26.0", "0.26.1") in 439ms
NoMethodError: undefined method `[]' for nil
	/action/judges/github-events/github-events.rb:52:in `block in fetch_contributors'
	/action/judges/github-events/github-events.rb:51:in `each'
	/action/judges/github-events/github-events.rb:51:in `fetch_contributors'
	/action/judges/github-events/github-events.rb:265:in `fill_up_event'
	/action/judges/github-events/github-events.rb:319:in `block (4 levels) in <top (required)>'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/looged.rb:65:in `block in txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/rules.rb:73:in `block in txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase.rb:168:in `txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/rules.rb:72:in `txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/pre.rb:62:in `txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/looged.rb:63:in `txn'
	/action/judges/github-events/github-events.rb:310:in `block (3 levels) in <top (required)>'
	/action/judges/github-events/github-events.rb:298:in `each'
	/action/judges/github-events/github-events.rb:298:in `each_with_index'
	/action/judges/github-events/github-events.rb:298:in `block (2 levels) in <top (required)>'
	/usr/local/bundle/gems/fbe-0.0.61/lib/fbe/iterate.rb:109:in `block (2 levels) in over'
	/usr/local/bundle/gems/fbe-0.0.61/lib/fbe/iterate.rb:88:in `each'
	/usr/local/bundle/gems/fbe-0.0.61/lib/fbe/iterate.rb:88:in `block in over'
```

### PR DESCRIPTION
**Pull request by Yegorov**
Closes #325

### CODE REVIEW

**Comment by Yegorov** [comment]
@Suban05 please review

**Review by Suban05 — APPROVED** [review]
@Yegorov perfect!

**Comment by yegor256** [comment]
@Yegorov thanks!

**Comment by 0crat** [comment]
@Yegorov Great work on your contribution! 🌟 You've earned +4 points, bringing your total to [+408](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). While we'd love to see more comments and hits-of-code in future submissions, we appreciate your effort. [Keep the contributions coming](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) – your work is valuable to our project!

**Comment by 0crat** [comment]
@Suban05 Hey there! 👋 Great job on the review, although it was a bit on the shorter side. You snagged 4 points for this one: 4 base points, -10 for only 3 comments (we're aiming for at least 6!), -8 because there were just 8 hits-of-code (we like to see 16+), and +18 to keep you in the game. Remember, more comments and code could boost your score next time! Your running balance is now [+395](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work and let's aim higher! 💪

**Pull request merged**
