### PR TITLE
#397: fix get actual repo name in github events

### LINKED ISSUE #397: TypeError: no implicit conversion of Symbol into Integer
I found it [here](https://github.com/objectionary/eo/actions/runs/11489045273/job/31977054048):

```
TypeError: no implicit conversion of Symbol into Integer
	/action/judges/github-events/github-events.rb:68:in `block in fetch_contributors'
	/usr/local/bundle/gems/sawyer-0.9.2/lib/sawyer/resource.rb:128:in `each'
	/usr/local/bundle/gems/sawyer-0.9.2/lib/sawyer/resource.rb:128:in `each'
	/action/judges/github-events/github-events.rb:67:in `fetch_contributors'
	/action/judges/github-events/github-events.rb:278:in `fill_up_event'
	/action/judges/github-events/github-events.rb:332:in `block (4 levels) in <top (required)>'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/looged.rb:65:in `block in txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/rules.rb:73:in `block in txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase.rb:168:in `txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/rules.rb:72:in `txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/pre.rb:62:in `txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/looged.rb:63:in `txn'
	/action/judges/github-events/github-events.rb:323:in `block (3 levels) in <top (required)>'
	/action/judges/github-events/github-events.rb:311:in `each'
	/action/judges/github-events/github-events.rb:311:in `each_with_index'
	/action/judges/github-events/github-events.rb:311:in `block (2 levels) in <top (required)>'
	/usr/local/bundle/gems/fbe-0.0.76/lib/fbe/iterate.rb:109:in `block (2 levels) in over'
	/usr/local/bundle/gems/fbe-0.0.76/lib/fbe/iterate.rb:88:in `each'
	/usr/local/bundle/gems/fbe-0.0.76/lib/fbe/iterate.rb:88:in `block in over']()
```

### PR DESCRIPTION
**Pull request by Yegorov**
Closes #397

### CODE REVIEW

**Comment by Yegorov** [comment]
@Suban05 please review

**Review by Suban05 — APPROVED** [review]
👍

**Comment by Yegorov** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@Yegorov thanks!

**Comment by 0crat** [comment]
@Yegorov Hey there! 👋 Awesome job on your contribution! You've snagged +7 points for this one: 4 points as the base reward, plus an extra 6 for those 133 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) you cranked out. We did have to deduct 4 points due to the low comment count (only 2), but don't sweat it! Remember, more comments can boost your score next time. Keep the code flowing and aim for that max 24-point reward! [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) up the great work! 💻🚀

**Pull request merged**
