### PR TITLE
#191: calculate average review comments size for pr

### LINKED ISSUE #191: `average_review_size` for QoS
Let's add `average_review_size` metric to the `quality-of-service.rb` script. It should calculate the average number of comments in a code review.

### PR DESCRIPTION
**Pull request by Yegorov**
Closes #191 
Fail, because need merge https://github.com/zerocracy/fbe/pull/93 first

### CODE REVIEW

**Review by Suban05 — APPROVED** [review]
@Yegorov looks good

**Comment by Yegorov** [comment]
@yegor256 please check

**Comment by Yegorov** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@Yegorov thanks!

**Comment by 0crat** [comment]
@Suban05 Hey there! 👋 Thanks for your review! You've earned +4 points this time. Here's the breakdown: +4 base points, -10 for having only 2 comments (policy suggests at least 6), and +10 to keep you motivated. Remember, more comments can boost your score next time! Your running balance is now [+341](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work and aim for those bonus points! 💪

**Comment by 0crat** [comment]
@Yegorov Hey there, great job on your contribution! 🎉 You've racked up 7 points for this one: 4 as the base, plus a nice boost for your 149 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html). We did have to deduct 4 points due to only having 3 comments during review - remember, more feedback helps everyone! Keep the code coming, and maybe aim for 6+ comments next time to avoid that deduction. Your balance is now at [+329](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Let's see if we can push that even higher with your next contribution. [Keep up](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the great work!

**Pull request merged**
