### PR TITLE
#239: ignore archived repos when count `total_repositories` in DoT

### LINKED ISSUE #239: `total_repositories` in DoT must ignore archived repos
`total_repositories` in `dimensions-of-terrain.rb` must ignore archived repos, don't count them.

### PR DESCRIPTION
**Pull request by Yegorov**
Closes #239

### CODE REVIEW

**Comment by Yegorov** [comment]
@Suban05 please review

**Review by Suban05 — APPROVED** [review]
@Yegorov looks good!

**Comment by Yegorov** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@Yegorov thanks!

**Comment by 0crat** [comment]
@Suban05 Hey there! 👋 Thanks for your review! You've earned +4 points, which is the minimum reward we give. Here's the breakdown: +4 base points, -24 for self-review, -10 for having less than 6 comments, and +0.25 for the single comment you made. We aim to encourage more detailed reviews, so try to leave at least 6 comments next time to avoid deductions. Your [running balance is +108](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work and remember, more comments can earn you up to 8 extra points! 💪

**Comment by 0crat** [comment]
@Yegorov Thanks for your contribution! Your reward of +6 points breaks down as follows: +4 base points, +6.15 for 123 hits-of-code (capped at +6), -4 for having only 2 comments (below the 6-comment threshold). Remember, more detailed code reviews can boost your points! Keep the [quality contributions](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) coming. Your current balance stands at [+158](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

**Pull request merged**
