### PR TITLE
#227: calculate average triage time for issues

### LINKED ISSUE #227: `average_triage_time` into QoS
Add `average_triage_time` to `quality-of-service` fact, where it's missing. It should be the average time in seconds between `issue-was-opened` and `bug-was-accepted` or `enhancement-was-accepted`.

### PR DESCRIPTION
**Pull request by Yegorov**
Closes #227

### CODE REVIEW

**Comment by Yegorov** [comment]
@Suban05 please review

**Review by Suban05 — APPROVED** [review]
@Yegorov looks good!

**Comment by Yegorov** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@Yegorov thanks!

**Comment by 0crat** [comment]
@Yegorov Great work on your contribution! 🎉 You've earned **10 points** for this effort: 4 base points, 9.85 points (capped at 9) for your 197 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html), and -4 points due to only 2 review comments. Remember, more review comments can boost your score next time. [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) up the good work! Your current balance stands at [+148](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

**Pull request merged**
