### PR TITLE
#203: calculate total number of unique contributors

### LINKED ISSUE #203: `total_contributors` into DoT
Let's add `total_contributors` metric to the `dimensions-of-terrain.rb` script. It should calculate the total number of unique contributors in all repositories.

### PR DESCRIPTION
**Pull request by Yegorov**
Closes #203

### CODE REVIEW

**Comment by Yegorov** [comment]
@Suban05 please review. Test fail, because this https://github.com/zerocracy/fbe/pull/106 PR need merge before

**Review by Suban05 — APPROVED** [review]
@Yegorov looks good!

**Comment by Yegorov** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@Yegorov thanks!

**Comment by 0crat** [comment]
@Suban05 Thanks for your code review! Here's how your +4 points were calculated: +4 base points, -24 for self-review, +16 for [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html), -10 for <6 comments, and +0.25 for the single comment. We adjusted to the minimum 4 points as per policy. Your balance is now [+130](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work! 💻

**Comment by 0crat** [comment]
@Yegorov Hey there! 👋 Great job on your contribution! You've earned +4 points this time. Here's the breakdown: +4 base points, -4 because there were only 2 comments (we love feedback!), and +4 to keep you motivated. Remember, more [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) and active code reviews can boost your points next time. [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions coming! Your current balance is [+168](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Looking forward to your next awesome commit! 🚀

**Pull request merged**
