### PR TITLE
202: calculate total number of files

### LINKED ISSUE #202: `total_files` into DoT
Let's add `total_files` metric to the `dimensions-of-terrain.rb` script. It should calculate the total number of files in all repositories. Maybe GitHub API can help us with this. If not, we probably need to `git clone` all repositories one by one and count files in them.

### PR DESCRIPTION
**Pull request by Yegorov**
Closes #202

### CODE REVIEW

**Comment by Yegorov** [comment]
@Suban05 please review. Test fail, because this https://github.com/zerocracy/fbe/pull/105 PR need merge before

**Review by Suban05 — APPROVED** [review]
@Yegorov fine!

**Comment by Yegorov** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@Yegorov thanks!

**Comment by 0crat** [comment]
@Suban05 Thanks for your code review! Here's how your points were calculated: +4 base points, -10 for having only 2 comments (policy requires 6+), and +10 to meet the minimum 4-point reward. Your total for this review is +4 points, bringing your running balance to [+134](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work, and remember that more detailed reviews with 6+ comments can earn you higher rewards! 💻👍

**Comment by 0crat** [comment]
@Yegorov 🎉 Great work! You've earned +5 points for your contribution: +4 base, +5 for 109 hits-of-code, -4 for minimal comments. [Keep up](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the momentum! Your current balance: [+182](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Looking forward to more quality submissions!

**Pull request merged**
