### PR TITLE
#166: add contributors to release-published fact in github-events

### PR DESCRIPTION
**Pull request by Yegorov**

### CODE REVIEW

**Comment by Yegorov** [comment]
@Suban05 can you review it, please?

**Review by Suban05 — APPROVED** [review]
@Yegorov looks very good

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@Suban05 Great job on the review! 🌟 You've earned +15 points: +25 base, with a -10 adjustment for limited comments (1). Your current balance stands at [+287](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work and consider adding more detailed feedback next time!

**Comment by 0crat** [comment]
@Yegorov Thank you for your contribution! Your effort has earned you +28 points: +25 base points, +8 for the 161 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) you wrote, and a -5 deduction due to the low number of review comments (only 3). We appreciate your work and encourage you to [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions coming. Remember, more detailed code reviews can help improve overall quality. Your updated running balance is [+166](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

**Pull request merged**
