### PR TITLE
#345: make popular options transmission directly to YAML configuration

### LINKED ISSUE #345: YAML configuration is too complex
Currently, we have to do this:

```
- uses: zerocracy/judges-action@0.0.52
  with:
    token: ${{ secrets.ZEROCRACY_TOKEN }}
    options: |
      github_token=${{ secrets.GITHUB_TOKEN }}
      repositories=...
    factbase: foo.fb
```

Would be nice to allow users to do just this:

```
- uses: zerocracy/judges-action@0.0.52
  with:
    token: ${{ secrets.ZEROCRACY_TOKEN }}
    github_token: ${{ secrets.GITHUB_TOKEN }}
    repositories: ...
    factbase: foo.fb
```

Thus, our plugin must understand most popular options and pass them through to the `options` argument of the `judges` tool.

### PR DESCRIPTION
**Pull request by Yegorov**
Closes #345

### CODE REVIEW

**Comment by Yegorov** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@Yegorov thanks!

**Comment by 0crat** [comment]
@Suban05 Great job on the review! 🌟 You've earned +4 points: +4 base, -10 for limited comments (2), but +10 to ensure recognition. Your current balance stands at [+60](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work and aim for more detailed feedback next time!

**Comment by 0crat** [comment]
@Yegorov Hey there! 👋 Nice work on your contribution! You've snagged +4 points for this one. Here's the breakdown: +4 base points, -4 because we only got 2 comments (we're aiming for at least 6), and +4 to keep you in the game. Remember, more [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) and active code reviews can boost your points next time. [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions flowing! Your current balance is [+86](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Let's aim higher together! 💪

**Pull request merged**
