### PR TITLE
#195: calculate total number of CI builds

### LINKED ISSUE #195: `total_builds_ran` into QoD
Let's add `total_builds_ran` metric to the `quantity-of-deliverables.rb` script. The metric should be the total number of CI builds executed in all repositories together, during the time since `$SINCE`.

### PR DESCRIPTION
**Pull request by Yegorov**
Closes #195

### CODE REVIEW

**Comment by Yegorov** [comment]
@Suban05 please review

**Review by Suban05 — APPROVED** [review]
@Yegorov fine

**Comment by Yegorov** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@Yegorov thanks!

**Comment by 0crat** [comment]
@Suban05 Thank you for your code review contribution! We appreciate your effort, but there's room for improvement. According to our policy, you've earned +4 points as a base reward. However, we had to deduct 10 points due to the low number of comments (only 1). To ensure a minimum reward, we've adjusted the total to +4 points. Remember, more detailed feedback helps the team grow. Your current balance stands at [+111](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work and aim for more comprehensive reviews in the future! 💻👍

**Comment by 0crat** [comment]
@Yegorov Hey there! 👋 Great job on your contribution! You've earned +4 points for this one. Here's the breakdown: +4 base points, -4 because we only had 2 comments (we aim for at least 6), and +4 to ensure you get something for your effort. Remember, more [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) and active code reviews can boost your points next time! [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions coming - you're doing great! Your current balance is [+149](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Looking forward to your next submission! 💻🚀

**Pull request merged**
