### PR TITLE
#380: add check for empty repositories in DoT

### LINKED ISSUE #380: check empty repositories in DoT
if we have an empty repo, we may get an error on the following line:
https://github.com/zerocracy/judges-action/blob/7afc6cd80ad0b0827072292644833b71ff4a7b93/judges/dimensions-of-terrain/dimensions-of-terrain.rb#L92

see https://github.com/zerocracy/judges-action/pull/379#pullrequestreview-2354710759

@yegor256 please take a look

### PR DESCRIPTION
**Pull request by Yegorov**
Closes #380

### CODE REVIEW

**Comment by Yegorov** [comment]
@Suban05 please review. Test fail, because this https://github.com/zerocracy/fbe/pull/115 PR need merge before

**Review by Suban05 — APPROVED** [review]
@Yegorov looks good

**Comment by Yegorov** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@Yegorov thanks!

**Comment by 0crat** [comment]
@Yegorov Thanks for your contribution! Here's the breakdown of your +4 points: +4 base, +0.1 for 2 hits-of-code, -4 for only 2 comments (our policy recommends at least 6). We've ensured you receive at least 4 points as per our policy. Remember, more [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) and thorough code reviews can boost your points significantly. [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions coming! Your current balance stands at [+140](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

**Comment by 0crat** [comment]
@Suban05 Hey there! 👋 Thanks for your code review! You've earned +4 points this time. Here's the breakdown: +4 base points, -10 for having only 3 comments (policy suggests at least 6), and +10 to ensure you get something meaningful. Remember, more comments can boost your points next time! Your current balance is [+104](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work and aim for those bonus points! 💪

**Pull request merged**
